# Generated by Django 4.1.5 on 2023-05-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('car_price', models.IntegerField(max_length=200)),
                ('car_link', models.URLField()),
            ],
        ),
    ]
