# Generated by Django 4.1.5 on 2023-05-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=50)),
                ('mobile_price', models.IntegerField(null=True)),
                ('mobile_link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='laptop_price',
            field=models.IntegerField(null=True),
        ),
    ]
